Repository appcelerator/titanium_mobile_windows, pull requests merged in 2018-11, with the labels that each got.

#1309 [7_5_X][TIMOB-26510] Workaround "layout cycle" issue
  Examples/kitchensink-v2/CMakeLists.txt
  Source/UI/src/ScrollView.cpp
Labels: in-qe-testing

#1306 [TIMOB-26510] Workaround "layout cycle" issue
  Examples/kitchensink-v2/CMakeLists.txt
  Source/UI/src/ScrollView.cpp
Labels: in-qe-testing

#1311 [TIMOB-26524] Can not compile folder with spaces
  templates/build/CMakeLists.txt.ejs
Labels: in-qe-testing

#1322 fix(build): Remove babel requires and unneeded babel traversal step
  cli/commands/_build/copy.js
Labels: bug

#1262 [TIMOB-26140] Move to Matrix2D and Matrix3D
  Source/TitaniumKit/include/Titanium/TiModule.hpp
  Source/TitaniumKit/include/Titanium/UIModule.hpp
  Source/TitaniumKit/src/TiModule.cpp
  Source/TitaniumKit/src/UI/2DMatrix.cpp
  Source/TitaniumKit/src/UI/3DMatrix.cpp
  Source/TitaniumKit/src/UIModule.cpp
  tests/Resources/ti.ui.2dmatrix.test.js
Labels: in-qe-testing

#1300 [TIMOB-25582] Add support for dp in ti.ui.defaultunit
  Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Labels: in-qe-testing

#1302 [TIMOB-26508] Setting undefined should clear layout value
  Source/LayoutEngine/src/ParseProperty.cpp
Labels: in-qe-testing

#1297 [TIMOB-26464] Add Ti.UI.Window.safeAreaPadding and extendSafeArea
  Source/TitaniumKit/CMakeLists.txt
  Source/TitaniumKit/include/Titanium/UI/ViewPadding.hpp
  Source/TitaniumKit/include/Titanium/UI/Window.hpp
  Source/TitaniumKit/src/UI/ViewPadding.cpp
  Source/TitaniumKit/src/UI/Window.cpp
Labels: in-qe-testing

#1301 [TIMOB-26503] Touch coordinate should not ignore default unit
  Source/TitaniumKit/include/Titanium/UI/Constants.hpp
  Source/TitaniumKit/src/UI/Constants.cpp
  Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
  Source/UI/src/WindowsViewLayoutDelegate.cpp
Labels: Waiting for CR

#1298 [TIMOB-26415] Added Ti.App "userinteraction" and "trackUserInteraction"
  Source/TitaniumKit/include/Titanium/App.hpp
  Source/TitaniumKit/src/App.cpp
  Source/UI/src/WindowsViewLayoutDelegate.cpp
Labels: Waiting for CR

#1320 [TIMOB-26562] Remove deprecated Ti.UI.KEYBOARD_* constants
  Source/TitaniumKit/include/Titanium/UIModule.hpp
  Source/TitaniumKit/src/UIModule.cpp
  apidoc/Titanium/UI.yml
Labels: Waiting for CR
