Repository appcelerator/titanium_mobile_windows, pull requests merged in 2018-10, with the labels that each got.

#1234 [TIMOB-26014] Ti.Media video recording is not working
  Source/Media/include/TitaniumWindows/Media.hpp
  Source/Media/src/Media.cpp
  Source/TitaniumKit/include/Titanium/Media/CameraOptionsType.hpp
  Source/TitaniumKit/src/Media/CameraMediaItemType.cpp
  Source/TitaniumKit/src/Media/CameraOptionsType.cpp
Labels: in-qe-testing

#1282 [TIMOB-26331] Improve build/launch time via Titanium CLI
  cli/commands/_build/checks.js
  cli/commands/_build/compile.js
  cli/commands/_build/copy.js
  cli/commands/_build/initialize.js
  cli/commands/_build/run.js
  cli/hooks/wp-run.js
  cli/hooks/ws-run.js
Labels: enhancement, in-qe-testing

#1288 [TIMOB-26403] Pass logger to analyzeJs call
  cli/commands/_build/copy.js
Labels: enhancement, in-qe-testing

#1183 [TIMOB-25774] Contact request should not block UI thread
  Source/Ti/include/TitaniumWindows/Contacts.hpp
  Source/Ti/include/TitaniumWindows/Contacts/Person.hpp
  Source/Ti/src/Contacts.cpp
  Source/Ti/src/Contacts/Person.cpp
  tests/Resources/ti.contacts.person.test.js
Labels: Waiting for CR

#1220 [TIMOB-25935] Ti.Utils.base64decode should ignore line breaks
  Source/TitaniumKit/src/Utils.cpp
  tests/Resources/ti.utils.test.js
Labels: bug, in-qe-testing

#1211 [TIMOB-25881] Implement WebView.blacklistedURLs
  Source/TitaniumKit/include/Titanium/UI/WebView.hpp
  Source/TitaniumKit/src/UI/WebView.cpp
  Source/UI/include/TitaniumWindows/UI/WebView.hpp
  Source/UI/src/WebView.cpp
Labels: Waiting for CR, enhancement

#1293 [TIMOB-26457] Window.exitOnClose parity
  Source/UI/src/Window.cpp
Labels: Waiting for CR
