Repository appcelerator/titanium_mobile_windows, pull requests merged in 2018-07, with the labels that each got.

#1204 [TIMOB-25796] Adding a hyperloop View multiple times throws error
  Source/UI/src/WindowsViewLayoutDelegate.cpp
Labels: in-qe-testing

#1267 [TIMOB-26115] Implement console.timeLog
  Source/TitaniumKit/src/TiModule.cpp
Labels: enhancement

#1215 [TIMOB-25891] Remove deprecated classes in Ti.Media
  Source/Media/include/TitaniumWindows/Media/AudioPlayer.hpp
  Source/Media/src/Media/AudioPlayer.cpp
Labels: in-qe-testing

#1181 [TIMOB-25352] Ti.Database.install should not prefix specified path
  Source/Titanium/src/File.cpp
  Source/TitaniumKit/src/DatabaseModule.cpp
Labels: bug

#1222 [TIMOB-25183] DefaultLanguage needs to be qualified
  cli/commands/_build/generate.js
Labels: in-qe-testing

#1230 [TIMOB-25983] Ti.UI.TextArea is not resized when its size is not specified
  Source/UI/include/TitaniumWindows/UI/TextArea.hpp
  Source/UI/src/TextArea.cpp
Labels: in-qe-testing
