Repository appcelerator/titanium_mobile_windows, pull requests merged in 2019-04, with the labels that each got.

#1376 Fix hang?
  .gitignore
  tests/Resources/app.js
Labels: work in progress 🚧

#1378 [TIMOB-26979] Save callback instances to stablize tests on Jenkins
  Source/Network/src/Socket/TCP.cpp
  Source/Network/src/Socket/UDP.cpp
  Source/UI/src/WebView.cpp
  tests/Resources/ti.ui.webview.test.js
Labels: DO NOT MERGE

#1380 [TIMOB-26969] Codec encodeNumber/decodeNumber should throw Error
  Source/TitaniumKit/src/Codec.cpp
  tests/Resources/ti.codec.test.js
Labels: in-qe-testing 🕵

#1384 [TIMOB-26986] Ti.App.uncaughtException is not fired
  Source/TitaniumKit/src/Application.cpp
Labels: in-qe-testing 🕵

#1369 [TIMOB-26855] Add "baseURL" support to WebView.setHtml()
  Source/UI/include/TitaniumWindows/UI/WebView.hpp
  Source/UI/src/WebView.cpp
Labels: in-qe-testing 🕵
